services:
  postgres:
    image: 'postgres:17.4'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'

  pgadmin:
    image: 'dpage/pgadmin4:9.2'
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8081:80"
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
      - source: pgpass
        target: /etc/pgpass

# https://stackoverflow.com/questions/64620446/adding-postgress-connections-to-pgadmin-in-docker-file
configs:
  pgpass:
    content: postgres:5432:*:myuser:secret
  servers.json:
    content: |
      {
        "Servers": {
            "1": {
                "Name": "demo DB",
                "Group": "Servers",
                "Host": "postgres",
                "Port": 5432,
                "MaintenanceDB": "mydatabase",
                "Username": "myuser",
                "ConnectionParameters": {
                  "passfile": "/etc/pgpass",
                }
            }
        }
      }