services:
  spring-boot:
    image: ghcr.io/hungyipntt/gaia-backend-spring-jpa-demo:v1
    environment:
      - SPRING_PROFILES_ACTIVE=demo-docker-compose
    ports:
      - "8080"

  postgres:
    image: 'postgres:17.4'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'

  pgadmin:
    image: 'dpage/pgadmin4:9.2'
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8081:80"