spring:
  application:
    name: gaia-backend-demo
  docker:
    compose:
      lifecycle-management: start-and-stop
  sql:
    init:
      mode: always

---
spring:
  profiles:
    active:
    - demo-docker-compose

  datasource:
    url: jdbc:postgressql:database://postgres:5432/mydatabase
    username: myuser
    password: secret