spring:
  application:
    name: gaia-backend-demo
  docker:
    compose:
      lifecycle-management: start-and-stop
  jpa:
    show-sql: true
  sql:
    init:
      platform: postgres
      mode: always
---
spring:
  config:
    activate:
      on-profile: 
      - unit-test

  sql:
    init:
      platform: postgres
      mode: always
      data-locations:
      - data-postgres-test.sql

  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true      
      
logging:
  level:
    org.springframework.test.context.jdbc: DEBUG
    org.springframework.jdbc.datasource.init: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
---
spring:
  config:
    activate:
      on-profile: 
      - demo-docker-compose

  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:postgresql://postgres:5432/mydatabase
    username: myuser
    password: secret

