spring:
  application:
    name: gaia-backend-demo
  docker:
    compose:
      lifecycle-management: start-and-stop
  sql:
    init:
      mode: always

---
spring:
  config:
    activate:
      on-profile: 
      - unit-test

  docker:
    compose:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: 
      - demo-docker-compose

  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:postgresql://postgres:5432/mydatabase
    username: myuser
    password: secret

